### ISSUE TITLE
Use with Nim web-framework?

### ISSUE THREAD

**Issue by Kentoseth** [h3rald/litestore#40]
Is it possible to use Litestore as a prototype-DB for a Nim web-framework?

I am currently tinkering with [Jester](https://github.com/dom96/jester) and I would like to add/edit/delete JSON (via the Jester-backend).

So instead of having Litestore be a client-facing datastore (as the documentation shows), I would instead like to use litestore in this manner:

```
Client <-> Jester-REST-API <-> litestore-DB
```

Is this possible to achieve?

If yes, are you able to share a small example in the readme file? It may help a lot of people that want to prototype small webapps with Jester+Litestore

Thanks!

**Comment by h3rald** [comment]
Interesting idea. Essentially you’d like to use LiteStore as a library — which is something I tend to forget to allow in my nim programs lately ;)

Technically it shouldn’t be too difficult: some suitable high-level methods are available in lib/api_v2.nim and they already even return Http responses, so it would fit nicely with your use case. I wonder if just requiring litestore/lib/api_v2 would do the trick...

I’ll do some tests and get back to you, and yes, I’ll add some examples to the guide as well.

Thanks!

**Comment by Kentoseth** [comment]
Yes, using litestore as a library within other programs :+1: 

It would technically be possible to achieve using litestore as-is, but that would require running the http-server and doing everything via API-requests, which wouldn't be as simplified as using Nim directly between Jester/litestore.

Thanks for checking.

I look forward to being able to use litestore within other nim programs :)

**Comment by h3rald** [comment]
I started looking into this. By adding a few export statements and modifiers I was able to expose all api_v2 procs so that they would be available when importing litestore.

At this point, I tried to write some jester routes to forwards, for example, certain get requests to litestore... and I stumbled onto a problem: Jester uses its own Request and Response types, while litestore uses the ones provided by the asynchttpserver! 

Pity, because it would have been trivial otherwise. Oh well, I guess I’ll have to come up with something else.

**Comment by Kentoseth** [comment]
Can you provide an example where Jesters req/resp conflicts with litestore?

I am assuming that when making a call to a litestore `proc` (eg. `GET`) it is returning an asynchttpserver Response type? Is this correct?

Jester also depends on asynchttpserver:

```
import asynchttpserver, net, strtabs, re, tables, parseutils, os, strutils, uri, 
scgi, cookies, times, mimetypes, asyncnet, asyncdispatch, macros,
 md5, logging, httpcore, asyncfile
```

Not sure if that helps with the situation/problem.

**Comment by h3rald** [comment]
Yes... but there was a problem with an ambiguous identifier in a file *in Jester* when importing asynchttpserver, litestore and jester together. Anyhow... good news! I think I sorted it out :)

Have a look at the **jester_integration.nim** file within the new examples folder - it should be what you are looking for: I was able to remap all LiteStore routes to Jester routes, and it seems to work!

The only thing I needed to do was converting a Jester Request into a LiteStore Request (which is basically an alias for asynchttpserver.Request), and then I was able to get it to work!

Now I guess I'll have to document all this new stuff properly and then realease a new version -- but meanwhile feel free to try it out and let me know if you're happy with it.

**EDIT**: I exposed additional high-level methods that don't use Request at all, so you don't have to create any conversion function anymore. Note that you probably would want to use regex routes in Jester so you can match LiteStore document IDs containing slashes.

I did some manual tests with some queries and it seems to work -- the only thing I didn't add (yet) is support for the "dir" LiteStore resource which is used to serve a mounted directory -- but I figured it's probably not that critical because Jester exposes a similar utility to serve files.

**Comment by Kentoseth** [comment]
I experimented a bit with `jester_integration.nim` (no changes, code as-is) by trying to POST some data to it. I tested a few curl requests to the server. These are the curl requests:

```
curl -H "Content-Type: application/json" -X POST -d '{"some":"data","some":"data"}'
 http://localhost:5000/litestore/docs/1

curl -X POST -d test.txt http://localhost:5000/litestore/docs/test

curl -X POST -d test.txt http://localhost:5000/litestore/docs/test.txt

curl -X POST -d test.txt http://localhost:5000/litestore/docs/1

curl -X POST -d test.txt http://localhost:5000/litestore/docs/

curl -X POST -d test.txt http://localhost:5000/litestore/docs/file.json
```
Every response I got was a 502:

```
WARN Could not parse URL query.
DEBUG POST /litestore/docs/file.json
ERROR Traceback (most recent call last)
jester_integration.nim(40) jester_integration
...
invalid format string
DEBUG   502 Bad Gateway {Content-Length: 1067, Content-Type: text/html;charset=utf-8}
```

Were you able to successfully POST data via Jester to litestore?

**Comment by h3rald** [comment]
Sorry for the late reply, I was on holiday and then at work :)

It should work now, here are some examples:

```
curl -H "Content-Type: application/json" -X POST -d '{"some":"data","some":"data"}' http://localhost:5000/litestore/docs/

curl -H "Content-Type: application/json" -X PUT -d '{"some":"data","some":"data"}' http://localhost:5000/litestore/docs/test1/aaa

curl -X DELETE http://localhost:5000/litestore/docs/test1/aaa

curl http://localhost:5000/litestore/docs/?search=data

curl -I http://localhost:5000/litestore/docs/

curl -X OPTIONS http://localhost:5000/litestore/docs/
```

I didn't test PATCH but it should work in the same way as the others. The examples for OPTIONS and HEAD are a bit... low-level, but they seem to work.

**Comment by h3rald** [comment]
The new API is now documented; closing this issue.
