### ISSUE TITLE
add an additional store with a conventional SQLite database

### ISSUE THREAD

**Issue by franko** [h3rald/litestore#56]
This is not really an issue but more an open question.

I am exploring Litestore to understand its possible usage. I read that you can add an additional store in a separate SQLite database but as far as I understand the additional databaset is used to store documents.

I was wondering if you can add a SQLite database to use it as a conventional SQL relational database to store application-specific tables. The idea is that an application may want to store some data in classical SQL tables. Then the application should be able to query this tables using javascript code from the client side or from the middleware side.

Otherwise it means that for any application that needs a classical SQL database in the backend Litestore cannot be used and one have to resort to the classical approach, for example, PHP with MySQL and Apache.

Is it possible ? Does it make sense ?

If not possible out of the box is there any way to "code around" Litestore to obtain access to raw SQLite tables ?

**Comment by h3rald** [comment]
Interesting functionality. Well, no, at the moment there's no way to do such a thing, but it is indeed possible to configure multiple stores (each with the same LiteStore schema though) to be served by the same server process.

Now, I created LiteStore because I wanted to be able to easily query a SQLite database using a REST API. The fact that LiteStore has a fixed schema made things easier and that also simplified database management (let's just say I changed the schema once, to add support for system documents).

Why would you want to do that though? You can already limit access to portions of the data store by creating JavaScript middleware... why would you want to query a traditional database? Technically it would be possible, it would be a matter of exposing some Js functions in duktape to query a SQLite database I guess. Not free, but not impossible either.

**Comment by franko** [comment]
> Why would you want to do that though?

Well I had in mind a SPA (single page app) where you need to visualize and possibly enter or edit data that is typically stored in a SQL databases. I guess you may store and visualize the data using a big json structure but that doesn't seem efficient especially if you know that you have SQLite under the hood and you may just directly use it the way it is supposed to be used.

I think the idea is sound. Beside the function "Add a new document" create a new function "Add a new database" and let the user add tables and queries and things like that. Then just add bridge to let the client-side javascript call a predefined database query in a RESTful way. At this point you can probably return the result of the query in json format to be consumed by the javascript.

This may greatly empower users giving them the power of a relational database without having to manage a server with MySQL or things like that.

**Comment by h3rald** [comment]
I kind of understand what you are after, but I don't think it would be a good idea for this project: the very point of LiteStore was to provide a NoSQL, schema-free data store, not an api for a relational database.

Maybe you are looking for something more like [SQLiteProxy](https://github.com/assafmo/SQLiteProxy)?
