### ISSUE TITLE
[QUESTION] Is there anyway to do simple authentication/login?

### ISSUE THREAD

**Issue by ajusa** [h3rald/litestore#60]
Hello,
I've read through most of the user guide and did notice the section that mentioned the JWT tokens being used for authentication. I'm not too familiar with those, but I understand the general idea. What I'm wondering is if it is possible to allow simple user creation and management using litestore itself? Or would you need a middleware to handle that?

For example, a TODO app that supports multiple users, and each user can only access their own lists.

I realize that this might be out of the scope of litestore, but sometimes I want to make a multi-user prototype for an application, and I don't understand how I could do that.
Thanks!

**Comment by h3rald** [comment]
Well... yes and no.

At present, the best (and most secure) way to prototype a multi-user web app with LiteStore is to use the built-in token validation functionality and delegate the authentication and user management part to a third-party identity provider. Personally I recommend Auth0 because it is easy to use, it has excellent docs, and a good free tier 😊

That being said, it would be technically possible to create web apps with some sort of built-in authentication using LiteStore middleware, because you can:
- customize URLs to access/deny access to users based on relatively arbitrary criteria
- get and set cookies via raw HTTP headers 
- store user data, sessions etc as (protected) LiteStore data

There is one (big) catch though: at the moment I don't think there's any way to generate hashes like sha1, sha256, or event md5 with the available JavaScript APIs provided by duktape. The good news is that it would be fairly easy to quickly code such functions in Nim and expose them in duktape so that you could use in middleware like the existing LiteStore-specific API methods.

Translated, this means that your user management system could only store user passwords in plain text, which would be probably fine for prototyping but really bad for production code.

I should provide a set of sample middleware to provide simple cookie-based authentication and a rudimentary user management system, I know... but at the moment my time is limited and using the few I have for my [min](https://min-lang.org) project. Then in a while I will stop working on it for a bit and go back to a "LiteStore phase"... 😊

Hope this helps somehow! If you have any more questions just ask!

**Comment by ajusa** [comment]
Yeah, that does help a lot actually! Personally, I think that it might be worth adding more user related functionality directly into litestore at some point (rather than limiting it to middleware), just because it is a really, really common pattern to allow user account creation for a lot of simple web apps. 

I suppose one could theoretically send the hashed password as a part of the form submit, rather than doing the hashing on the server side to get around the duktape limitations, that seems like a potential avenue for creating/managing user accounts. Seems like it might require a decent amount of middleware code though, really depends on how one would approach it.

I completely understand that you're giving min more time, I use it every once in a while as well (I made a few issues in the repository around three years ago?). Should I leave this issue open as a reminder to (eventually) work on a user management system for you, or should I close it? Seems like you've answered my question very well :smile:

**Comment by h3rald** [comment]
Oh yes leave this issue open! I am not sure if it would be worthwhile to change the database schema to include users (...and roles? Permissions? Who knows!). I hardly ever change the schema. But at worst it would be cool to have at least some fully working middleware for a basic authentication/authorization system.

**Comment by ajusa** [comment]
Sure, that makes sense. I only proposed changing the schema due to potential performance concerns, as I know that duktape isn't super fast (but you don't want to add V8 for sure, that's like 30mb). Another (good?) reason to change the schema would be to not be able to change authentication, so that it is baked in. I find it easier to trust your code to be secure than I find trusting mine :smile:. However, working middleware mostly addresses that issue as well. 

If it is possible to add middleware authentication that is both performant, easy to get set up, and secure, then by all means I would love that option.

If you want to bounce ideas off of me in the future, feel free.
